services:
  # Backend API Service
  - type: web
    name: favbooks-backend
    env: python
    region: oregon
    plan: free
    branch: master
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        value: sqlite:///./bookdb.sqlite3

