services:
  # Backend API Service
  - type: web
    name: favbooks-backend
    env: python
    region: oregon
    plan: free
    branch: master
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        value: sqlite:///./bookdb.sqlite3
    healthCheckPath: /
    
  # Frontend Static Site
  - type: static
    name: favbooks-frontend
    env: static
    region: oregon
    plan: free
    branch: master
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: favbooks-backend
          envVarKey: RENDER_EXTERNAL_URL
