services:
  - type: web
    name: favbooks-api
    runtime: python
    region: oregon
    plan: free
    branch: master
  rootDir: .
  buildCommand: pip install -r backend/requirements.txt
  startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        value: sqlite:///./whichbook.db
    healthCheckPath: /health
